### ISSUE TITLE
Using ESP32-WROOM instead ESP32-WROVER? 8MB or 4MB?

### ISSUE THREAD

**Issue by katyurua** [dukeduck1984/uReflowOven-Esp32-Micropython#19]
#### Can I use ESP32-WROOM?
***
#### Can I use 4MB module?

**Comment by dukeduck1984** [comment]
yes, you can.  either 4mb or 8mb will work.

**Comment by dukeduck1984** [comment]
pls flash the firmware included in this repo.

**Comment by katyurua** [comment]
thanks
