### ISSUE TITLE
搜索不到WIFI信号

### ISSUE THREAD

**Issue by BG7YWL** [dukeduck1984/uReflowOven-Esp32-Micropython#8]
使用ESP32烧录座+ESP32-WROVER-B模块的方式烧录固件发现无法搜索到WIFI型号，ES32-WROOM-32模块也有尝试
![微信图片_20200706182024](https://user-images.githubusercontent.com/9145406/86583284-96e81780-bfb5-11ea-8916-3394a1ceb417.jpg)
![Snipaste_2020-07-06_18-21-31](https://user-images.githubusercontent.com/9145406/86583277-9485bd80-bfb5-11ea-8d2c-0b9dbd2e2661.png)
![Snipaste_2020-07-06_18-21-46](https://user-images.githubusercontent.com/9145406/86583281-964f8100-bfb5-11ea-9090-37743ce6606d.png)

**Comment by dukeduck1984** [comment]
我试了手头的两块Esp32 Wroom，都没有问题呀
```
>>> import network
>>> sta = network.WLAN(network.STA_IF)
>>> sta.active(True)
I (68968) phy: phy_version: 4102, 2fa7a43, Jul 15 2019, 13:06:06, 0, 0
True
>>> sta.scan()
[(b'28#301_ASUS', b'p\x8b\xcd\xc8\xba ', 1, -20, 3, False), (b'28#301_ASUS', b'\x0c\x12bb\xb7{', 1, -47, 3, False), (b'28#301_MI', b'\xecA\x18]
>>>
```

自己作为AP，或者作为station去连接别的AP也都正常

你贴的图上我也没看到报错信息

**Comment by BG7YWL** [comment]
通过AMPY工具，我已经将MAIN目录下所有文件、文件夹都上传到ESP32中，但是还是没有WIFI信号。
![Snipaste_2020-07-07_17-26-12](https://user-images.githubusercontent.com/9145406/86759256-fd813a00-c076-11ea-9142-dcebfcb6f9fa.png)

另外我参考config.json文件，只看出以下的接线，有部分引脚接线不知道怎么接，比如TFT_ACC和MAX31855模块的HWSPI、CS、MISO、SCK，我按照你说的模块购买上面并没有这些引脚。
| TFT | ESP32 |
| ------------ | ------------ |
| T_IRQ | 35 |
| T_DO |   |
| T_DIN |   |
| T_CS | 25 |
| T_CLK |   |
| MISO | 5 |
| LED | 15 |
| MOSI | 18 |
| DC | 12 |
| RST | 4 |
| CS | 13 |
| GND | GND |
| VCC | 3V3 |

| BUZZ | ESP32 |
| ------------ | ------------ |
| GND | GND |
| I/O | 22 |
| VCC | 3V3 |

| MAX31855 | ESP32 |
| ------------ | ------------ |
| GND | GND |
| VCC | 3V3 |
| DO |  |
| CS |  |
| CLK |  |

**Comment by dukeduck1984** [comment]
TFT的ACC是给屏幕供电的GPIO，接到屏幕的VCC上，但实际上你把屏幕的VCC直接接到3.3V即可，程序本身并没有关闭屏幕的操作。T_DO直接并联到TFT的MISO，T_DIN并联到TFT的MOSI，T_CLK并联到TFT的SCK。

MAX31855的DO就是MISO，CLK就是SCK。hwspi是硬件spi的编号，不是GPIO，mpy文档里有写。

你硬件线没接好的话，main.py执行的时候肯定在初始化硬件的时候就出错终止了，不会执行到最后打开AP信号的代码，所以没有wifi信号。
